### ISSUE TITLE
documentation is extremly lacking

### ISSUE THREAD

**Issue by BabylonSix** [jadejs/jade-filters#10]
ok, so I spent an entire day trying to get jade filters to work with gulp, namely, markdown, stylus, and coffeescript

the jade documentation is not helpful
http://jade-lang.com/reference/filters/

the jstransformers page it points to is not helpful
https://github.com/jstransformers/jstransformer

the gulp-jstransform page is not helpful
https://github.com/jstransformers/gulp-jstransformer

the jstransformer-stylus page is not helpful
https://www.npmjs.com/package/jstransformer-stylus

the conversations on the subject are not helpful at all
https://github.com/jstransformers/jstransformer/issues/17
https://github.com/jadejs/jade/pull/1928

Please guys, not everyone is a javascript ninja, get your documentation on the subject easier to understand. If filters are a part of jade, how can they be implemented in something like gulp?

There's not gulp gists with an example, nothing relavent I could find through hours of looking through google searches and stack overflow, I feel like I'm going in circles. Please help.

Thank you for your time.

**Comment by TimothyGu** [comment]
Documentation has been a major focus for us, as seen in tickets such as jadejs/jade#2052. For this specific topic on filters, I have recently added a good amount of docs on this matter (jadejs/jade#2078). Because we have not had a release yet with the documentation improvements, the new docs are not visible on the website, but you can see it at https://github.com/jadejs/jade/blob/master/docs/views/reference/filters.jade.

For your specific case, simply installing the jstransformers you need _should_ suffice: `npm i --save jstransformer-stylus` etc. I have added some more documentation on this in jadejs/jade#2113.

For future reference, we do not support anything not under the @jadejs umbrella, which includes external modules like gulp-jade. In fact, I personally do not have any idea how Gulp works at all, but the installation process above applies to Jade in general.

And next time, unless you know **exactly** what a jade module does, file an issue in the main repo at jadejs/jade :)

**Comment by BabylonSix** [comment]
HOLY SHIT MAN! ^___^

Y__Y You’re a genius! O__O

It works better than I imagined!
